# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\dayo-sscom.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import * 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 553)
        MainWindow.setMinimumSize(QtCore.QSize(740, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_recv = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_recv.setObjectName("groupBox_recv")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_recv)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit_rx_data = QtWidgets.QTextEdit(self.groupBox_recv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_rx_data.sizePolicy().hasHeightForWidth())
        self.textEdit_rx_data.setSizePolicy(sizePolicy)
        self.textEdit_rx_data.setReadOnly(True)
        self.textEdit_rx_data.setObjectName("textEdit_rx_data")
        self.verticalLayout_3.addWidget(self.textEdit_rx_data)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_clear_rx = QtWidgets.QPushButton(self.groupBox_recv)
        self.pushButton_clear_rx.setObjectName("pushButton_clear_rx")
        self.horizontalLayout_3.addWidget(self.pushButton_clear_rx)
        self.pushButton_savedata = QtWidgets.QPushButton(self.groupBox_recv)
        self.pushButton_savedata.setObjectName("pushButton_savedata")
        self.horizontalLayout_3.addWidget(self.pushButton_savedata)
        self.checkBox_automatic_savedata = QtWidgets.QCheckBox(self.groupBox_recv)
        self.checkBox_automatic_savedata.setObjectName("checkBox_automatic_savedata")
        self.horizontalLayout_3.addWidget(self.checkBox_automatic_savedata)
        self.lineEdit_search = QtWidgets.QLineEdit(self.groupBox_recv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_search.sizePolicy().hasHeightForWidth())
        self.lineEdit_search.setSizePolicy(sizePolicy)
        self.lineEdit_search.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_search.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout_3.addWidget(self.lineEdit_search)
        self.pushButton_search = QtWidgets.QPushButton(self.groupBox_recv)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout_3.addWidget(self.pushButton_search)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.groupBox_at = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_at.sizePolicy().hasHeightForWidth())
        self.groupBox_at.setSizePolicy(sizePolicy)
        self.groupBox_at.setMinimumSize(QtCore.QSize(220, 0))
        self.groupBox_at.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBox_at.setObjectName("groupBox_at")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_at)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 202, 295))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_hex = QtWidgets.QLabel(self.layoutWidget)
        self.label_hex.setObjectName("label_hex")
        self.horizontalLayout_4.addWidget(self.label_hex)
        self.label_at_cmd = QtWidgets.QLabel(self.layoutWidget)
        self.label_at_cmd.setObjectName("label_at_cmd")
        self.horizontalLayout_4.addWidget(self.label_at_cmd)
        self.label_at_send = QtWidgets.QLabel(self.layoutWidget)
        self.label_at_send.setObjectName("label_at_send")
        self.horizontalLayout_4.addWidget(self.label_at_send)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_hex_cmd1 = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_hex_cmd1.sizePolicy().hasHeightForWidth())
        self.checkBox_hex_cmd1.setSizePolicy(sizePolicy)
        self.checkBox_hex_cmd1.setMaximumSize(QtCore.QSize(15, 16777215))
        self.checkBox_hex_cmd1.setText("")
        self.checkBox_hex_cmd1.setObjectName("checkBox_hex_cmd1")
        self.horizontalLayout_5.addWidget(self.checkBox_hex_cmd1)
        self.lineEdit_cmd1 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cmd1.sizePolicy().hasHeightForWidth())
        self.lineEdit_cmd1.setSizePolicy(sizePolicy)
        self.lineEdit_cmd1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_cmd1.setObjectName("lineEdit_cmd1")
        self.horizontalLayout_5.addWidget(self.lineEdit_cmd1)
        self.pushButton_cmd1 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cmd1.sizePolicy().hasHeightForWidth())
        self.pushButton_cmd1.setSizePolicy(sizePolicy)
        self.pushButton_cmd1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_cmd1.setObjectName("pushButton_cmd1")
        self.horizontalLayout_5.addWidget(self.pushButton_cmd1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_hex_cmd2 = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_hex_cmd2.sizePolicy().hasHeightForWidth())
        self.checkBox_hex_cmd2.setSizePolicy(sizePolicy)
        self.checkBox_hex_cmd2.setMaximumSize(QtCore.QSize(15, 16777215))
        self.checkBox_hex_cmd2.setText("")
        self.checkBox_hex_cmd2.setObjectName("checkBox_hex_cmd2")
        self.horizontalLayout_8.addWidget(self.checkBox_hex_cmd2)
        self.lineEdit_cmd2 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cmd2.sizePolicy().hasHeightForWidth())
        self.lineEdit_cmd2.setSizePolicy(sizePolicy)
        self.lineEdit_cmd2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_cmd2.setObjectName("lineEdit_cmd2")
        self.horizontalLayout_8.addWidget(self.lineEdit_cmd2)
        self.pushButton_cmd2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cmd2.sizePolicy().hasHeightForWidth())
        self.pushButton_cmd2.setSizePolicy(sizePolicy)
        self.pushButton_cmd2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_cmd2.setObjectName("pushButton_cmd2")
        self.horizontalLayout_8.addWidget(self.pushButton_cmd2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_hex_cmd3 = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_hex_cmd3.sizePolicy().hasHeightForWidth())
        self.checkBox_hex_cmd3.setSizePolicy(sizePolicy)
        self.checkBox_hex_cmd3.setMaximumSize(QtCore.QSize(15, 16777215))
        self.checkBox_hex_cmd3.setText("")
        self.checkBox_hex_cmd3.setObjectName("checkBox_hex_cmd3")
        self.horizontalLayout_9.addWidget(self.checkBox_hex_cmd3)
        self.lineEdit_cmd3 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cmd3.sizePolicy().hasHeightForWidth())
        self.lineEdit_cmd3.setSizePolicy(sizePolicy)
        self.lineEdit_cmd3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_cmd3.setObjectName("lineEdit_cmd3")
        self.horizontalLayout_9.addWidget(self.lineEdit_cmd3)
        self.pushButton_cmd3 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cmd3.sizePolicy().hasHeightForWidth())
        self.pushButton_cmd3.setSizePolicy(sizePolicy)
        self.pushButton_cmd3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_cmd3.setObjectName("pushButton_cmd3")
        self.horizontalLayout_9.addWidget(self.pushButton_cmd3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_hex_cmd4 = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_hex_cmd4.sizePolicy().hasHeightForWidth())
        self.checkBox_hex_cmd4.setSizePolicy(sizePolicy)
        self.checkBox_hex_cmd4.setMaximumSize(QtCore.QSize(15, 16777215))
        self.checkBox_hex_cmd4.setText("")
        self.checkBox_hex_cmd4.setObjectName("checkBox_hex_cmd4")
        self.horizontalLayout_10.addWidget(self.checkBox_hex_cmd4)
        self.lineEdit_cmd4 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cmd4.sizePolicy().hasHeightForWidth())
        self.lineEdit_cmd4.setSizePolicy(sizePolicy)
        self.lineEdit_cmd4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_cmd4.setObjectName("lineEdit_cmd4")
        self.horizontalLayout_10.addWidget(self.lineEdit_cmd4)
        self.pushButton_cmd4 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cmd4.sizePolicy().hasHeightForWidth())
        self.pushButton_cmd4.setSizePolicy(sizePolicy)
        self.pushButton_cmd4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_cmd4.setObjectName("pushButton_cmd4")
        self.horizontalLayout_10.addWidget(self.pushButton_cmd4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_hex_cmd5 = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_hex_cmd5.sizePolicy().hasHeightForWidth())
        self.checkBox_hex_cmd5.setSizePolicy(sizePolicy)
        self.checkBox_hex_cmd5.setMaximumSize(QtCore.QSize(15, 16777215))
        self.checkBox_hex_cmd5.setText("")
        self.checkBox_hex_cmd5.setObjectName("checkBox_hex_cmd5")
        self.horizontalLayout_11.addWidget(self.checkBox_hex_cmd5)
        self.lineEdit_cmd5 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cmd5.sizePolicy().hasHeightForWidth())
        self.lineEdit_cmd5.setSizePolicy(sizePolicy)
        self.lineEdit_cmd5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_cmd5.setObjectName("lineEdit_cmd5")
        self.horizontalLayout_11.addWidget(self.lineEdit_cmd5)
        self.pushButton_cmd5 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cmd5.sizePolicy().hasHeightForWidth())
        self.pushButton_cmd5.setSizePolicy(sizePolicy)
        self.pushButton_cmd5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_cmd5.setObjectName("pushButton_cmd5")
        self.horizontalLayout_11.addWidget(self.pushButton_cmd5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_hex_cmd6 = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_hex_cmd6.sizePolicy().hasHeightForWidth())
        self.checkBox_hex_cmd6.setSizePolicy(sizePolicy)
        self.checkBox_hex_cmd6.setMaximumSize(QtCore.QSize(15, 16777215))
        self.checkBox_hex_cmd6.setText("")
        self.checkBox_hex_cmd6.setObjectName("checkBox_hex_cmd6")
        self.horizontalLayout_12.addWidget(self.checkBox_hex_cmd6)
        self.lineEdit_cmd6 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cmd6.sizePolicy().hasHeightForWidth())
        self.lineEdit_cmd6.setSizePolicy(sizePolicy)
        self.lineEdit_cmd6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_cmd6.setObjectName("lineEdit_cmd6")
        self.horizontalLayout_12.addWidget(self.lineEdit_cmd6)
        self.pushButton_cmd6 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cmd6.sizePolicy().hasHeightForWidth())
        self.pushButton_cmd6.setSizePolicy(sizePolicy)
        self.pushButton_cmd6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_cmd6.setObjectName("pushButton_cmd6")
        self.horizontalLayout_12.addWidget(self.pushButton_cmd6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBox_hex_cmd7 = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_hex_cmd7.sizePolicy().hasHeightForWidth())
        self.checkBox_hex_cmd7.setSizePolicy(sizePolicy)
        self.checkBox_hex_cmd7.setMaximumSize(QtCore.QSize(15, 16777215))
        self.checkBox_hex_cmd7.setText("")
        self.checkBox_hex_cmd7.setObjectName("checkBox_hex_cmd7")
        self.horizontalLayout_13.addWidget(self.checkBox_hex_cmd7)
        self.lineEdit_cmd7 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cmd7.sizePolicy().hasHeightForWidth())
        self.lineEdit_cmd7.setSizePolicy(sizePolicy)
        self.lineEdit_cmd7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_cmd7.setObjectName("lineEdit_cmd7")
        self.horizontalLayout_13.addWidget(self.lineEdit_cmd7)
        self.pushButton_cmd7 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cmd7.sizePolicy().hasHeightForWidth())
        self.pushButton_cmd7.setSizePolicy(sizePolicy)
        self.pushButton_cmd7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_cmd7.setObjectName("pushButton_cmd7")
        self.horizontalLayout_13.addWidget(self.pushButton_cmd7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBox_hex_cmd8 = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_hex_cmd8.sizePolicy().hasHeightForWidth())
        self.checkBox_hex_cmd8.setSizePolicy(sizePolicy)
        self.checkBox_hex_cmd8.setMaximumSize(QtCore.QSize(15, 16777215))
        self.checkBox_hex_cmd8.setText("")
        self.checkBox_hex_cmd8.setObjectName("checkBox_hex_cmd8")
        self.horizontalLayout_14.addWidget(self.checkBox_hex_cmd8)
        self.lineEdit_cmd8 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cmd8.sizePolicy().hasHeightForWidth())
        self.lineEdit_cmd8.setSizePolicy(sizePolicy)
        self.lineEdit_cmd8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_cmd8.setObjectName("lineEdit_cmd8")
        self.horizontalLayout_14.addWidget(self.lineEdit_cmd8)
        self.pushButton_cmd8 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cmd8.sizePolicy().hasHeightForWidth())
        self.pushButton_cmd8.setSizePolicy(sizePolicy)
        self.pushButton_cmd8.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_cmd8.setObjectName("pushButton_cmd8")
        self.horizontalLayout_14.addWidget(self.pushButton_cmd8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBox_at_crlf = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_at_crlf.setObjectName("checkBox_at_crlf")
        self.horizontalLayout_15.addWidget(self.checkBox_at_crlf)
        self.pushButton_atcmd_save = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_atcmd_save.setObjectName("pushButton_atcmd_save")
        self.horizontalLayout_15.addWidget(self.pushButton_atcmd_save)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_serial_set = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_serial_set.setObjectName("groupBox_serial_set")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_serial_set)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 21, 138, 85))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_com = QtWidgets.QLabel(self.layoutWidget1)
        self.label_com.setObjectName("label_com")
        self.horizontalLayout_17.addWidget(self.label_com)
        self.comboBox_com = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_com.setObjectName("comboBox_com")
        self.horizontalLayout_17.addWidget(self.comboBox_com)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_baudrate = QtWidgets.QLabel(self.layoutWidget1)
        self.label_baudrate.setObjectName("label_baudrate")
        self.horizontalLayout_18.addWidget(self.label_baudrate)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_baudrate)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_refresh_serial = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_refresh_serial.sizePolicy().hasHeightForWidth())
        self.pushButton_refresh_serial.setSizePolicy(sizePolicy)
        self.pushButton_refresh_serial.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_refresh_serial.setObjectName("pushButton_refresh_serial")
        self.horizontalLayout_6.addWidget(self.pushButton_refresh_serial)
        self.pushButton_open_serial = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_serial.sizePolicy().hasHeightForWidth())
        self.pushButton_open_serial.setSizePolicy(sizePolicy)
        self.pushButton_open_serial.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_open_serial.setObjectName("pushButton_open_serial")
        self.horizontalLayout_6.addWidget(self.pushButton_open_serial)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.frame = QtWidgets.QFrame(self.layoutWidget1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7.addWidget(self.frame)
        self.horizontalLayout_2.addWidget(self.groupBox_serial_set)
        self.groupBox_mcu_download = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_mcu_download.setObjectName("groupBox_mcu_download")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_mcu_download)
        self.verticalLayout_2.setContentsMargins(-1, 9, 9, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lineEdit_mcu_bat_file = QtWidgets.QLineEdit(self.groupBox_mcu_download)
        self.lineEdit_mcu_bat_file.setObjectName("lineEdit_mcu_bat_file")
        self.horizontalLayout_19.addWidget(self.lineEdit_mcu_bat_file)
        self.toolButton_mcu_bat_file = QtWidgets.QToolButton(self.groupBox_mcu_download)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_mcu_bat_file.sizePolicy().hasHeightForWidth())
        self.toolButton_mcu_bat_file.setSizePolicy(sizePolicy)
        self.toolButton_mcu_bat_file.setObjectName("toolButton_mcu_bat_file")
        self.horizontalLayout_19.addWidget(self.toolButton_mcu_bat_file)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.pushButton_start_download = QtWidgets.QPushButton(self.groupBox_mcu_download)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start_download.sizePolicy().hasHeightForWidth())
        self.pushButton_start_download.setSizePolicy(sizePolicy)
        self.pushButton_start_download.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_start_download.setObjectName("pushButton_start_download")
        self.verticalLayout_2.addWidget(self.pushButton_start_download)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 6)
        self.horizontalLayout_2.addWidget(self.groupBox_mcu_download)
        self.groupBox_device_id = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_device_id.setObjectName("groupBox_device_id")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_device_id)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lineEdit_device_id = QtWidgets.QLineEdit(self.groupBox_device_id)
        self.lineEdit_device_id.setObjectName("lineEdit_device_id")
        self.horizontalLayout_16.addWidget(self.lineEdit_device_id)
        self.checkBox_id_crlf = QtWidgets.QCheckBox(self.groupBox_device_id)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_id_crlf.sizePolicy().hasHeightForWidth())
        self.checkBox_id_crlf.setSizePolicy(sizePolicy)
        self.checkBox_id_crlf.setObjectName("checkBox_id_crlf")
        self.horizontalLayout_16.addWidget(self.checkBox_id_crlf)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.pushButton_write_id = QtWidgets.QPushButton(self.groupBox_device_id)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_write_id.sizePolicy().hasHeightForWidth())
        self.pushButton_write_id.setSizePolicy(sizePolicy)
        self.pushButton_write_id.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_write_id.setObjectName("pushButton_write_id")
        self.verticalLayout_6.addWidget(self.pushButton_write_id)
        self.horizontalLayout_2.addWidget(self.groupBox_device_id)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 23))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_set = QtWidgets.QMenu(self.menubar)
        self.menu_set.setObjectName("menu_set")
        self.menuLogLevel = QtWidgets.QMenu(self.menu_set)
        self.menuLogLevel.setObjectName("menuLogLevel")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Quit = QtWidgets.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.actionCOM = QtWidgets.QAction(MainWindow)
        self.actionCOM.setObjectName("actionCOM")
        self.actionBaudrate = QtWidgets.QAction(MainWindow)
        self.actionBaudrate.setObjectName("actionBaudrate")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionWriteIDCmd = QtWidgets.QAction(MainWindow)
        self.actionWriteIDCmd.setObjectName("actionWriteIDCmd")
        self.actionlogdebug = QtWidgets.QAction(MainWindow)
        self.actionlogdebug.setCheckable(True)
        self.actionlogdebug.setObjectName("actionlogdebug")
        self.actionloginfo = QtWidgets.QAction(MainWindow)
        self.actionloginfo.setCheckable(True)
        self.actionloginfo.setObjectName("actionloginfo")
        self.actionlogwarning = QtWidgets.QAction(MainWindow)
        self.actionlogwarning.setCheckable(True)
        self.actionlogwarning.setObjectName("actionlogwarning")
        self.actionlogerror = QtWidgets.QAction(MainWindow)
        self.actionlogerror.setCheckable(True)
        self.actionlogerror.setObjectName("actionlogerror")
        self.menu_file.addAction(self.action_Open)
        self.menu_file.addAction(self.action_Quit)
        self.menuLogLevel.addAction(self.actionlogdebug)
        self.menuLogLevel.addAction(self.actionloginfo)
        self.menuLogLevel.addAction(self.actionlogwarning)
        self.menuLogLevel.addAction(self.actionlogerror)
        self.menu_set.addAction(self.actionCOM)
        self.menu_set.addAction(self.actionBaudrate)
        self.menu_set.addAction(self.actionWriteIDCmd)
        self.menu_set.addAction(self.menuLogLevel.menuAction())
        self.menu_help.addAction(self.actionhelp)
        self.menu_help.addAction(self.actionabout)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_set.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_recv.setTitle(_translate("MainWindow", "接收"))
        self.textEdit_rx_data.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">此程序是北京大友智造科技有限公司工厂生产工具，</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">请先配置好端口号、波特率，然后打开串口。</p></body></html>"))
        self.pushButton_clear_rx.setText(_translate("MainWindow", "清空窗口"))
        self.pushButton_savedata.setText(_translate("MainWindow", "保存数据"))
        self.checkBox_automatic_savedata.setText(_translate("MainWindow", "自动保存数据"))
        self.pushButton_search.setText(_translate("MainWindow", "查找"))
        self.groupBox_at.setTitle(_translate("MainWindow", "AT指令"))
        self.label_hex.setText(_translate("MainWindow", "Hex"))
        self.label_at_cmd.setText(_translate("MainWindow", "命令"))
        self.label_at_send.setText(_translate("MainWindow", "     发送"))
        self.pushButton_cmd1.setText(_translate("MainWindow", "发送"))
        self.pushButton_cmd2.setText(_translate("MainWindow", "发送"))
        self.pushButton_cmd3.setText(_translate("MainWindow", "发送"))
        self.pushButton_cmd4.setText(_translate("MainWindow", "发送"))
        self.pushButton_cmd5.setText(_translate("MainWindow", "发送"))
        self.pushButton_cmd6.setText(_translate("MainWindow", "发送"))
        self.pushButton_cmd7.setText(_translate("MainWindow", "发送"))
        self.pushButton_cmd8.setText(_translate("MainWindow", "发送"))
        self.checkBox_at_crlf.setText(_translate("MainWindow", "加回车换行"))
        self.pushButton_atcmd_save.setText(_translate("MainWindow", "保存指令"))
        self.groupBox_serial_set.setTitle(_translate("MainWindow", "串口设置"))
        self.label_com.setText(_translate("MainWindow", "端口号"))
        self.label_baudrate.setText(_translate("MainWindow", "波特率"))
        self.comboBox_baudrate.setItemText(0, _translate("MainWindow", "1200"))
        self.comboBox_baudrate.setItemText(1, _translate("MainWindow", "2400"))
        self.comboBox_baudrate.setItemText(2, _translate("MainWindow", "4800"))
        self.comboBox_baudrate.setItemText(3, _translate("MainWindow", "9600"))
        self.comboBox_baudrate.setItemText(4, _translate("MainWindow", "115200"))
        self.pushButton_refresh_serial.setText(_translate("MainWindow", "刷新"))
        self.pushButton_open_serial.setText(_translate("MainWindow", "打开串口"))
        self.groupBox_mcu_download.setTitle(_translate("MainWindow", "单片机程序下载"))
        self.toolButton_mcu_bat_file.setText(_translate("MainWindow", "..."))
        self.pushButton_start_download.setText(_translate("MainWindow", "开始下载"))
        self.groupBox_device_id.setTitle(_translate("MainWindow", "设备地址"))
        self.checkBox_id_crlf.setText(_translate("MainWindow", "加回车换行"))
        self.pushButton_write_id.setText(_translate("MainWindow", "写入设备ID"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.menu_set.setTitle(_translate("MainWindow", "设置"))
        self.menuLogLevel.setTitle(_translate("MainWindow", "LogLevel"))
        self.menu_help.setTitle(_translate("MainWindow", "帮助"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Quit.setText(_translate("MainWindow", "&Quit"))
        self.actionCOM.setText(_translate("MainWindow", "COM"))
        self.actionBaudrate.setText(_translate("MainWindow", "Baudrate"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionabout.setText(_translate("MainWindow", "?"))
        self.actionWriteIDCmd.setText(_translate("MainWindow", "WriteIDCmd"))
        self.actionlogdebug.setText(_translate("MainWindow", "debug"))
        self.actionloginfo.setText(_translate("MainWindow", "info"))
        self.actionlogwarning.setText(_translate("MainWindow", "warning"))
        self.actionlogerror.setText(_translate("MainWindow", "error"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = QMainWindow()
    gui = Ui_MainWindow()
    gui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
